// Auto-generated Wails bindings — regenerated by `wails generate module`.
// This file is a typed stub; the real implementation is injected at runtime.

import type {
  Label,
  Session,
  TimerProfile,
  TimerState,
  AppSettings,
  CloudSyncStatus,
  CloudHistoryEntry,
  CloudTimelineEntry,
  Summary,
  TimelineEntry,
  ListRequest,
  UpdateRequest,
  BulkEditRequest,
  SummaryRequest,
  TimelineRequest,
  CreateLabelRequest,
  UpdateLabelRequest,
  SettingsUpdateRequest,
} from "../../../types";

type WailsRuntime = { go: { main: { App: Record<string, (...a: unknown[]) => Promise<unknown>> } } };

function call<T>(method: string, ...args: unknown[]): Promise<T> {
  return (window as unknown as WailsRuntime).go.main.App[method](...args) as Promise<T>;
}

// Timer
export const StartTimer = (): Promise<void>        => call("StartTimer");
export const PauseTimer = (): Promise<void>        => call("PauseTimer");
export const ResumeTimer = (): Promise<void>       => call("ResumeTimer");
export const StopTimer = (): Promise<void>         => call("StopTimer");
export const SkipTimer = (): Promise<void>         => call("SkipTimer");
export const GetTimerState = (): Promise<TimerState> => call("GetTimerState");
export const ApplyTimerProfile = (): Promise<void>   => call("ApplyTimerProfile");
export const ResetCompletedSessions = (): Promise<void> => call("ResetCompletedSessions");
export const SetMiniMode = (enabled: boolean): Promise<void> => call("SetMiniMode", enabled);

// Labels
export const GetLabels = (): Promise<Label[]>                              => call("GetLabels");
export const CreateLabel = (req: CreateLabelRequest): Promise<Label>      => call("CreateLabel", req);
export const UpdateLabel = (req: UpdateLabelRequest): Promise<void>       => call("UpdateLabel", req);
export const DeleteLabel = (name: string): Promise<void>                  => call("DeleteLabel", name);
export const ArchiveLabel = (name: string): Promise<void>                 => call("ArchiveLabel", name);
export const UnarchiveLabel = (name: string): Promise<void>               => call("UnarchiveLabel", name);
export const ReorderLabels = (names: string[]): Promise<void>             => call("ReorderLabels", names);
export const SetActiveLabel = (name: string): Promise<void>               => call("SetActiveLabel", name);

// Sessions
export const GetSessions = (req: ListRequest): Promise<Session[]>         => call("GetSessions", req);
export const UpdateSession = (req: UpdateRequest): Promise<void>          => call("UpdateSession", req);
export const DeleteSessions = (ids: number[]): Promise<void>              => call("DeleteSessions", ids);
export const BulkEditLabel = (req: BulkEditRequest): Promise<void>        => call("BulkEditLabel", req);

// Statistics
export const GetStatisticsSummary = (req: SummaryRequest): Promise<Summary>      => call("GetStatisticsSummary", req);
export const GetTimelineData = (req: TimelineRequest): Promise<TimelineEntry[]>  => call("GetTimelineData", req);

// Settings
export const GetSettings = (): Promise<AppSettings>                              => call("GetSettings");
export const UpdateSettings = (req: SettingsUpdateRequest): Promise<void>        => call("UpdateSettings", req);
export const GetTimerProfiles = (): Promise<TimerProfile[]>                      => call("GetTimerProfiles");
export const SaveTimerProfile = (p: TimerProfile): Promise<void>                 => call("SaveTimerProfile", p);
export const SaveTimerProfilesToCloud = (): Promise<void>                        => call("SaveTimerProfilesToCloud");
export const DeleteTimerProfile = (name: string): Promise<void>                  => call("DeleteTimerProfile", name);
export const SyncProfilesFromCloud = (): Promise<number>                         => call("SyncProfilesFromCloud");

// Backup
export const ExportBackup = (): Promise<string>  => call("ExportBackup");
export const ImportBackup = (): Promise<void>    => call("ImportBackup");

// Cloud Sync
export const SaveToCloud = (): Promise<CloudSyncStatus>               => call("SaveToCloud");
export const GetCredentialsPath = (): Promise<string>                 => call("GetCredentialsPath");
export const CloudSyncEnabled = (): Promise<boolean>                  => call("CloudSyncEnabled");
export const GetCloudSyncSchedule = (): Promise<string>               => call("GetCloudSyncSchedule");
export const SetCloudSyncSchedule = (schedule: string): Promise<void> => call("SetCloudSyncSchedule", schedule);

// Combined Cloud Data
export const RefreshCloudData = (): Promise<void>                                      => call("RefreshCloudData");
export const GetCombinedHistory = (): Promise<CloudHistoryEntry[]>                     => call("GetCombinedHistory");
export const GetCombinedTimeline = (): Promise<CloudTimelineEntry[]>                   => call("GetCombinedTimeline");
