// Auto-generated Wails bindings — regenerated by `wails generate module`.
// This file is a typed stub; the real implementation is injected at runtime.

import type {
  Label,
  Session,
  TimerProfile,
  TimerState,
  AppSettings,
  Summary,
  TimelineEntry,
  ListRequest,
  UpdateRequest,
  BulkEditRequest,
  SummaryRequest,
  TimelineRequest,
  CreateLabelRequest,
  UpdateLabelRequest,
  SettingsUpdateRequest,
} from "../../../types";

function call<T>(method: string, ...args: unknown[]): Promise<T> {
  return (window as unknown as Record<string, Record<string, (...a: unknown[]) => Promise<T>>>)
    .go.main.App[method](...args);
}

// Timer
export const StartTimer = (): Promise<void>        => call("StartTimer");
export const PauseTimer = (): Promise<void>        => call("PauseTimer");
export const ResumeTimer = (): Promise<void>       => call("ResumeTimer");
export const StopTimer = (): Promise<void>         => call("StopTimer");
export const SkipTimer = (): Promise<void>         => call("SkipTimer");
export const GetTimerState = (): Promise<TimerState> => call("GetTimerState");

// Labels
export const GetLabels = (): Promise<Label[]>                              => call("GetLabels");
export const CreateLabel = (req: CreateLabelRequest): Promise<Label>      => call("CreateLabel", req);
export const UpdateLabel = (req: UpdateLabelRequest): Promise<void>       => call("UpdateLabel", req);
export const DeleteLabel = (name: string): Promise<void>                  => call("DeleteLabel", name);
export const ArchiveLabel = (name: string): Promise<void>                 => call("ArchiveLabel", name);
export const UnarchiveLabel = (name: string): Promise<void>               => call("UnarchiveLabel", name);
export const ReorderLabels = (names: string[]): Promise<void>             => call("ReorderLabels", names);
export const SetActiveLabel = (name: string): Promise<void>               => call("SetActiveLabel", name);

// Sessions
export const GetSessions = (req: ListRequest): Promise<Session[]>         => call("GetSessions", req);
export const UpdateSession = (req: UpdateRequest): Promise<void>          => call("UpdateSession", req);
export const DeleteSessions = (ids: number[]): Promise<void>              => call("DeleteSessions", ids);
export const BulkEditLabel = (req: BulkEditRequest): Promise<void>        => call("BulkEditLabel", req);

// Statistics
export const GetStatisticsSummary = (req: SummaryRequest): Promise<Summary>      => call("GetStatisticsSummary", req);
export const GetTimelineData = (req: TimelineRequest): Promise<TimelineEntry[]>  => call("GetTimelineData", req);

// Settings
export const GetSettings = (): Promise<AppSettings>                              => call("GetSettings");
export const UpdateSettings = (req: SettingsUpdateRequest): Promise<void>        => call("UpdateSettings", req);
export const GetTimerProfiles = (): Promise<TimerProfile[]>                      => call("GetTimerProfiles");
export const SaveTimerProfile = (p: TimerProfile): Promise<void>                 => call("SaveTimerProfile", p);
export const DeleteTimerProfile = (name: string): Promise<void>                  => call("DeleteTimerProfile", name);

// Backup
export const ExportBackup = (): Promise<string>  => call("ExportBackup");
export const ImportBackup = (): Promise<void>    => call("ImportBackup");
