// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTimerProfile() {
  return window['go']['main']['App']['ApplyTimerProfile']();
}

export function ArchiveLabel(arg1) {
  return window['go']['main']['App']['ArchiveLabel'](arg1);
}

export function BulkEditLabel(arg1) {
  return window['go']['main']['App']['BulkEditLabel'](arg1);
}

export function CloudSyncEnabled() {
  return window['go']['main']['App']['CloudSyncEnabled']();
}

export function CreateLabel(arg1) {
  return window['go']['main']['App']['CreateLabel'](arg1);
}

export function DeleteLabel(arg1) {
  return window['go']['main']['App']['DeleteLabel'](arg1);
}

export function DeleteSessions(arg1) {
  return window['go']['main']['App']['DeleteSessions'](arg1);
}

export function DeleteTimerProfile(arg1) {
  return window['go']['main']['App']['DeleteTimerProfile'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function GetCloudSyncSchedule() {
  return window['go']['main']['App']['GetCloudSyncSchedule']();
}

export function GetCombinedHistory() {
  return window['go']['main']['App']['GetCombinedHistory']();
}

export function GetCombinedTimeline() {
  return window['go']['main']['App']['GetCombinedTimeline']();
}

export function GetCredentialsPath() {
  return window['go']['main']['App']['GetCredentialsPath']();
}

export function GetLabels() {
  return window['go']['main']['App']['GetLabels']();
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatisticsSummary(arg1) {
  return window['go']['main']['App']['GetStatisticsSummary'](arg1);
}

export function GetTimelineData(arg1) {
  return window['go']['main']['App']['GetTimelineData'](arg1);
}

export function GetTimerProfiles() {
  return window['go']['main']['App']['GetTimerProfiles']();
}

export function GetTimerState() {
  return window['go']['main']['App']['GetTimerState']();
}

export function GetUnsyncedSessions() {
  return window['go']['main']['App']['GetUnsyncedSessions']();
}

export function ImportBackup() {
  return window['go']['main']['App']['ImportBackup']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function PushSelectedSessions(arg1) {
  return window['go']['main']['App']['PushSelectedSessions'](arg1);
}

export function RefreshCloudData() {
  return window['go']['main']['App']['RefreshCloudData']();
}

export function ReorderLabels(arg1) {
  return window['go']['main']['App']['ReorderLabels'](arg1);
}

export function ResetCompletedSessions() {
  return window['go']['main']['App']['ResetCompletedSessions']();
}

export function ResumeTimer() {
  return window['go']['main']['App']['ResumeTimer']();
}

export function SaveTimerProfile(arg1) {
  return window['go']['main']['App']['SaveTimerProfile'](arg1);
}

export function SaveTimerProfilesToCloud() {
  return window['go']['main']['App']['SaveTimerProfilesToCloud']();
}

export function SaveToCloud() {
  return window['go']['main']['App']['SaveToCloud']();
}

export function SetActiveLabel(arg1) {
  return window['go']['main']['App']['SetActiveLabel'](arg1);
}

export function SetCloudSyncSchedule(arg1) {
  return window['go']['main']['App']['SetCloudSyncSchedule'](arg1);
}

export function SetMiniMode(arg1) {
  return window['go']['main']['App']['SetMiniMode'](arg1);
}

export function SkipTimer() {
  return window['go']['main']['App']['SkipTimer']();
}

export function StartTimer() {
  return window['go']['main']['App']['StartTimer']();
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}

export function SyncProfilesFromCloud() {
  return window['go']['main']['App']['SyncProfilesFromCloud']();
}

export function UnarchiveLabel(arg1) {
  return window['go']['main']['App']['UnarchiveLabel'](arg1);
}

export function UpdateLabel(arg1) {
  return window['go']['main']['App']['UpdateLabel'](arg1);
}

export function UpdateSession(arg1) {
  return window['go']['main']['App']['UpdateSession'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
