// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sessions} from '../models';
import {labels} from '../models';
import {database} from '../models';
import {main} from '../models';
import {timer} from '../models';
import {settings} from '../models';

export function ApplyTimerProfile():Promise<void>;

export function ArchiveLabel(arg1:string):Promise<void>;

export function BulkEditLabel(arg1:sessions.BulkEditRequest):Promise<void>;

export function CloudSyncEnabled():Promise<boolean>;

export function CreateLabel(arg1:labels.CreateRequest):Promise<database.Label>;

export function DeleteLabel(arg1:string):Promise<void>;

export function DeleteSessions(arg1:Array<number>):Promise<void>;

export function DeleteTimerProfile(arg1:string):Promise<void>;

export function ExportBackup():Promise<string>;

export function GetCloudSyncSchedule():Promise<string>;

export function GetCombinedHistory():Promise<Array<main.CloudHistoryEntry>>;

export function GetCombinedTimeline():Promise<Array<main.CloudTimelineEntry>>;

export function GetCredentialsPath():Promise<string>;

export function GetLabels():Promise<Array<database.Label>>;

export function GetSessions(arg1:sessions.ListRequest):Promise<Array<database.Session>>;

export function GetSettings():Promise<database.AppSettings>;

export function GetStatisticsSummary(arg1:sessions.SummaryRequest):Promise<sessions.Summary>;

export function GetTimelineData(arg1:sessions.TimelineRequest):Promise<Array<sessions.TimelineEntry>>;

export function GetTimerProfiles():Promise<Array<database.TimerProfile>>;

export function GetTimerState():Promise<timer.State>;

export function ImportBackup():Promise<void>;

export function PauseTimer():Promise<void>;

export function RefreshCloudData():Promise<void>;

export function ReorderLabels(arg1:Array<string>):Promise<void>;

export function ResetCompletedSessions():Promise<void>;

export function ResumeTimer():Promise<void>;

export function SaveTimerProfile(arg1:database.TimerProfile):Promise<void>;

export function SaveTimerProfilesToCloud():Promise<void>;

export function SaveToCloud():Promise<main.CloudSyncStatus>;

export function SetActiveLabel(arg1:string):Promise<void>;

export function SetCloudSyncSchedule(arg1:string):Promise<void>;

export function SetMiniMode(arg1:boolean):Promise<void>;

export function SkipTimer():Promise<void>;

export function StartTimer():Promise<void>;

export function StopTimer():Promise<void>;

export function SyncProfilesFromCloud():Promise<number>;

export function UnarchiveLabel(arg1:string):Promise<void>;

export function UpdateLabel(arg1:labels.UpdateRequest):Promise<void>;

export function UpdateSession(arg1:sessions.UpdateRequest):Promise<void>;

export function UpdateSettings(arg1:settings.UpdateRequest):Promise<void>;
